name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: |
          docker build -f Dockerfile -t reqover/reqover-proxy:latest .
    - name: Push
      run: |
          docker push reqover/reqover-proxy:latest
    - name: Tag image
      run: |
          docker tag reqover/reqover:latest reqover/reqover-proxy:${GITHUB_SHA::8}
    - name: Push tagged
      run: |
          docker push reqover/reqover-proxy:${GITHUB_SHA::8}